### ISSUE TITLE
Add tuxedo-keyboard

### ISSUE THREAD

**Issue by ruzko** [ublue-os/akmods#30]
### Describe the package

[Tuxedo-keyboard](https://github.com/tuxedocomputers/tuxedo-keyboard) adds drivers for keyboard backlight, fan control and other hardware enablements on Tuxedo Computers and other laptops using Clevo chassis.

Only available as dkms at the moment, [although I have opened an issue about kmod availability](https://github.com/tuxedocomputers/tuxedo-keyboard/issues/120)

### Image

All Images

**Comment by castrojo** [comment]
Status is we need to just find someone with the time to implement this.

**Comment by david** [comment]
@castrojo I'd be happy to help with this, but other than copying and changing the build script, I'm not quite sure what kind environment I need to build and test my changes. Could you point me to some documentation that will help me set up things? I apologize for my noobness if there is something I missed. :disappointed:

**Comment by HikariKnight** [comment]
i ported looking-glass official dkms to akmods with the guidance of kyle, i can help too if youre in the EU timezone (however i am very busy from august 12th to the 22th)

you can look at what i did here to make the spec file :)
https://github.com/HikariKnight/looking-glass-kvmfr-akmod

**Comment by salim-b** [comment]
> i ported looking-glass official dkms to akmods with the guidance of kyle, i can help too if youre in the EU timezone (however i am very busy from august 12th to the 22th)
> 
> you can look at what i did here to make the spec file :) https://github.com/HikariKnight/looking-glass-kvmfr-akmod

@Matombo @vinzv Maybe you could help?

**Comment by andrea-nisti** [comment]
any update on this? I would love this feature, I am currently using kinoite on a tuxedo "linux compatible" laptop but unable to install their drivers. Unfortunately I am too ignorant on driver development so idk how to help in this, I could always test it on my hardware though

**Comment by tobehn** [comment]
Are you aware of tuxedo-rs from Aaron Erhardt?
https://aaronerhardt.github.io/blog/posts/announcing_tuxedo_rs/
https://github.com/AaronErhardt/tuxedo-rs

i am using a tuxedo infinitybook pro 16 - i want to update it to bluefin soon.
Is there anything i can contribute to implement the tuxedo stuff into bluefin?

**Comment by castrojo** [comment]
Yeah we need someone to make it: https://github.com/ublue-os/akmods?tab=readme-ov-file#adding-kmods

**Comment by opentux** [comment]
hi,
thanks for the info on akmod. (i'm going to do some tests)
in fact it has changed a lot at tuxedo

no more need for the copr they have their fedora repository

https://www.tuxedocomputers.com/en/Add-TUXEDO-software-package-sources.tuxedo

https://rpm.tuxedocomputers.com/fedora/

then the control center takes care of fine energy management, overclocking, the rgb keyboard, and on some machines there is even watercooling management (the pump is controlled by bluetooth).

i have an old machine for work, and a much more recent one that has everything available from the control center.

in any case the control center today has taken a much more important place than just the simple support of the keyboard...

but i will do tests if i can do things on my side or not

**Comment by salim-b** [comment]
@opentux The [TUXEDO Control Center (TCC)](https://github.com/tuxedocomputers/tuxedo-control-center) is not the issue here but the additional out-of-tree Linux kernel modules that TCC and similar software like [tuxedo-rs](https://github.com/AaronErhardt/tuxedo-rs) require to properly work. These kernel modules are provided by TUXEDO and developed as a project called [tuxedo-drivers](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers). IIUC, the main problem is that they require [DKMS](https://en.wikipedia.org/wiki/Dynamic_Kernel_Module_Support) which is fundamentally incompatible with immutable Linux distros, so tuxedo-drivers would first need to be ported to akmods as [pointed out by \@HikariKnight](https://github.com/ublue-os/akmods/issues/30#issuecomment-2266721809).

**Comment by opentux** [comment]
thank you for the additional information, well in any case no longer use the copr which is clearly not up to date since the creation of the official tuxedo repository regardless of the distribution. whether for tuxedo-drivers or tcc

**Comment by gladion136** [comment]
Hi,
I tried to port the Tuxedo-drivers to kmod. [Here](https://github.com/gladion136/tuxedo-drivers-kmod) is the current status.
I can load the modules on my hardware. But there are still some Issues.. I would like to create a PR here when everything works fine.

However, a few paths seem to be missing, which is why [tuxedo-backlight-control](https://github.com/webketje/tuxedo-backlight-control) e.g. does not work. The files `/sys/class/leds/rgb:kbd_backlight/color_*` and `/sys/class/leds/rgb:kbd_backlight/state` are missing. 
However, I can set the color of the keyboard via `/sys/class/leds/rgb:kbd_backlight/multi_intensity`.

Unfortunately I have not yet managed to get [tuxedo-rs](https://github.com/AaronErhardt/tuxedo-rs) running. 

When I start it I get the following error:

<details>
  <summary>Click to expand! - tailord error</summary>

```
Nov 23 21:47:46 bluefin tailord[11915]: thread 'main' panicked at /var/home/eschmidt/github/tuxedo-rs/tailord/_build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-uring-0.5.0/src/lib.rs:148:48:
Nov 23 21:47:46 bluefin tailord[11915]: called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
Nov 23 21:47:46 bluefin tailord[11915]: stack backtrace:
Nov 23 21:47:46 bluefin tailord[11915]:    0:     0x56395c60a665 - std::backtrace_rs::backtrace::libunwind::trace::h23054e327d0d4b55
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
Nov 23 21:47:46 bluefin tailord[11915]:    1:     0x56395c60a665 - std::backtrace_rs::backtrace::trace_unsynchronized::h0cc587407d7f7f64
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
Nov 23 21:47:46 bluefin tailord[11915]:    2:     0x56395c60a665 - std::sys_common::backtrace::_print_fmt::h4feeb59774730d6b
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:68:5
Nov 23 21:47:46 bluefin tailord[11915]:    3:     0x56395c60a665 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:44:22
Nov 23 21:47:46 bluefin tailord[11915]:    4:     0x56395c63697b - core::fmt::rt::Argument::fmt::h105051d8ea1ade1e
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/rt.rs:165:63
Nov 23 21:47:46 bluefin tailord[11915]:    5:     0x56395c63697b - core::fmt::write::hc6043626647b98ea
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/fmt/mod.rs:1168:21
Nov 23 21:47:46 bluefin tailord[11915]:    6:     0x56395c60717f - std::io::Write::write_fmt::h0d24b3e0473045db
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/io/mod.rs:1835:15
Nov 23 21:47:46 bluefin tailord[11915]:    7:     0x56395c60a43e - std::sys_common::backtrace::_print::h62df6fc36dcebfc8
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:47:5
Nov 23 21:47:46 bluefin tailord[11915]:    8:     0x56395c60a43e - std::sys_common::backtrace::print::h45eb8174d25a1e76
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:34:9
Nov 23 21:47:46 bluefin tailord[11915]:    9:     0x56395c60b7d9 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
Nov 23 21:47:46 bluefin tailord[11915]:   10:     0x56395c60b57a - std::panicking::default_hook::hb5d3b27aa9f6dcda
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:298:9
Nov 23 21:47:46 bluefin tailord[11915]:   11:     0x56395c60bc73 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:795:13
Nov 23 21:47:46 bluefin tailord[11915]:   12:     0x56395c60bb54 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:664:13
Nov 23 21:47:46 bluefin tailord[11915]:   13:     0x56395c60ab29 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:171:18
Nov 23 21:47:46 bluefin tailord[11915]:   14:     0x56395c60b887 - rust_begin_unwind
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
Nov 23 21:47:46 bluefin tailord[11915]:   15:     0x56395be2dc53 - core::panicking::panic_fmt::ha02418e5cd774672
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
Nov 23 21:47:46 bluefin tailord[11915]:   16:     0x56395be2e1c6 - core::result::unwrap_failed::h55f86ada3ace5ed2
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
Nov 23 21:47:46 bluefin tailord[11915]:   17:     0x56395be3e4bd - core::result::Result<T,E>::unwrap::ha43169bc23e975b7
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1102:23
Nov 23 21:47:46 bluefin tailord[11915]:   18:     0x56395be3e4bd - tokio_uring::start::hee2a91d45485a0cd
Nov 23 21:47:46 bluefin tailord[11915]:                                at /var/home/eschmidt/github/tuxedo-rs/tailord/_build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/tokio-uring-0.5.0/src/lib.rs:148:14
Nov 23 21:47:46 bluefin tailord[11915]:   19:     0x56395bf63c51 - tailord::main::h2cbe143c430c7dd3
Nov 23 21:47:46 bluefin tailord[11915]:                                at /var/home/eschmidt/github/tuxedo-rs/tailord/src/main.rs:39:5
Nov 23 21:47:46 bluefin tailord[11915]:   20:     0x56395be952ab - core::ops::function::FnOnce::call_once::h4503de3c873adaef
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
Nov 23 21:47:46 bluefin tailord[11915]:   21:     0x56395bf2064e - std::sys_common::backtrace::__rust_begin_short_backtrace::hc461f41eda36bfaa
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/sys_common/backtrace.rs:155:18
Nov 23 21:47:46 bluefin tailord[11915]:   22:     0x56395be3a071 - std::rt::lang_start::{{closure}}::hdfef758b209ac421
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:159:18
Nov 23 21:47:46 bluefin tailord[11915]:   23:     0x56395c60247d - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf57beef1b8c334ce
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:284:13
Nov 23 21:47:46 bluefin tailord[11915]:   24:     0x56395c60247d - std::panicking::try::do_call::h65791b6ab5d9b39f
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
Nov 23 21:47:46 bluefin tailord[11915]:   25:     0x56395c60247d - std::panicking::try::h5a3dd25e8a379a23
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
Nov 23 21:47:46 bluefin tailord[11915]:   26:     0x56395c60247d - std::panic::catch_unwind::he2ce8403bab77de2
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
Nov 23 21:47:46 bluefin tailord[11915]:   27:     0x56395c60247d - std::rt::lang_start_internal::{{closure}}::h0b55d0da19178545
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:141:48
Nov 23 21:47:46 bluefin tailord[11915]:   28:     0x56395c60247d - std::panicking::try::do_call::h33cbeb674c7644e0
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
Nov 23 21:47:46 bluefin tailord[11915]:   29:     0x56395c60247d - std::panicking::try::h530c58b4c9daadba
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
Nov 23 21:47:46 bluefin tailord[11915]:   30:     0x56395c60247d - std::panic::catch_unwind::h92e02677901e11e4
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
Nov 23 21:47:46 bluefin tailord[11915]:   31:     0x56395c60247d - std::rt::lang_start_internal::hcee5ed89fc25829a
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:141:20
Nov 23 21:47:46 bluefin tailord[11915]:   32:     0x56395be3a04a - std::rt::lang_start::hae76945278770748
Nov 23 21:47:46 bluefin tailord[11915]:                                at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/rt.rs:158:17
Nov 23 21:47:46 bluefin tailord[11915]:   33:     0x56395bf63c9e - main
Nov 23 21:47:46 bluefin tailord[11915]:   34:     0x7f03361aa248 - __libc_start_call_main
Nov 23 21:47:46 bluefin tailord[11915]:   35:     0x7f03361aa30b - __libc_start_main_impl
Nov 23 21:47:47 bluefin tailord[11915]:   36:     0x56395be2e785 - _start
Nov 23 21:47:47 bluefin tailord[11915]:   37:                0x0 - <unknown>
Nov 23 21:47:47 bluefin systemd[1]: tailord.service: Main process exited, code=exited, status=101/n/a
```

</details>

Can anyone help me or give me a tip?

**Comment by bastian-src** [comment]
Hey @gladion136 👋 

> I have observed that in some missing installations (on other distributions) not all options are displayed in the UI of the Tuxedo Control Center. I have attached screenshots, can someone check if something is missing?

I'm running Pop OS 22.04 on my Tuxedo XMG Fusion 15 L19 and I have the same options in my Tuxedo Control Center as shown in your screenshots.

**Comment by LeonardoMantovani** [comment]
So, noob question here to see if I'm getting this right:
- pre-installing the TCC app on Bluefin/Aurora would be easy, but for it to work also tuxedo-drivers must be installed
- pre-installing tuxedo-drivers is "less easy", because they are built using dkms and therefore need to be ported to kmod
- @gladion136 is working on this port, that at the time of writing is working with TCC properly, but not with tuxedo-rs (that I think I haven't understood what it is and why is it needed though)
- as soon as their work is done and fully functional, tuxedo-drivers and TCC are ready to be integrated with Bluefin / Aurora

Is this correct? And if so, would installing those 2 extra packages be something each tuxedo user should do or a custom ISO for tuxedo computers will be provided?

Btw thank you all for the great work you are doing on this!

**Comment by gladion136** [comment]
Hey, that's right. The TCC app only works with the [tuxedo-drivers](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers). I have ported these to akmods as [tuxedo-drivers-kmod](https://github.com/gladion136/tuxedo-drivers-kmod). Currently there are still a few issues I'm working on. Currently tuxedo-drivers-kmod works with the TCC app. 

- However, I have not yet got [tuxedo-rs](https://github.com/AaronErhardt/tuxedo-rs) to run on bluefin. There I still have authorization problems with the DBUS interface. [Here](https://github.com/ublue-os/akmods/issues/30#issuecomment-2495687756) is the log.
- I also haven't gotten [tuxedo-backlight-control](https://github.com/webketje/tuxedo-backlight-control) to run yet, because a few paths are missing (as described [here](https://github.com/ublue-os/akmods/issues/30#issuecomment-2495687756)). I don't know what the problem is. 
- The power saving settings between Gnome and the TCC app are not synchronized. I don't know if this is normal or if they are not compatible together.


As soon as the problems are solved I will publish the port on copr and create a PR to this repository. 

If anyone has any ideas for my problems I would appreciate your help. 

I don't think the TCC app and drivers will be included in the general Bluefin. It could be publish as a variant (like dx, ..).
It would be possible to include the drivers always, because if they don't fit they simply won't load. But the TCC app could cause confusion as it doesn't make sense on non Tuxedo laptops.
However, this is not my decision, but that of the ublue-os maintainers. I don't know what procedure is desired there.

**Comment by salim-b** [comment]
> tuxedo-rs (that I think I haven't understood what it is and why is it needed though)

tuxedo-rs is an unofficial alternative to TCC. Main (supposed) upsides of tuxedo-rs are

- ressource-efficiency and safety/robustness since it is written in [Rust](https://en.wikipedia.org/wiki/Rust_(programming_language)), while TCC is built on [Electron](https://en.wikipedia.org/wiki/Electron_(software_framework)) ([software bloat](https://en.wikipedia.org/wiki/Electron_(software_framework)#Reception)) and written in Typescript and Python.

- native look on Gnome since its UI is built on [libadwaita](https://gtk-rs.org/gtk4-rs/stable/latest/book/libadwaita.html), while TCC is built on Electron.

So I would expect that tuxedo-rs is clearly superior to TCC. But I haven't yet tried it myself, I gotta admit.

---

> The power saving settings between Gnome and the TCC app are not synchronized. I don't know if this is normal or if they are not compatible together.

They aren't synchronized either when tuxedo-drivers is installed via DKMS (e.g. on Ubuntu). I could imagine tuxedo-drivers does not use/implement (all) the Linux kernel APIs it should (which would fit what they write [here](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers#regarding-upstreaming-of-tuxedo-drivers) about the drivers not being in an "upstreamable state").

**Comment by LeonardoMantovani** [comment]
> If anyone has any ideas for my problems I would appreciate your help.

Unfortunately I know too little both about rust and about linux kernel and its module to help directly, but I can provide logs from a "traditional" installation (with tuxedo-drivers and TCC on an Ubuntu system) I'll be happy to help!

**Comment by BrickMan240** [comment]
Hey everyone! 

I'm not a member of the Universal Blue project, but I did something with @gladion136's efforts and the custom image template by Universal Blue: Pulling various Aurora, Bluefin and Bazzite images and modifying them to include Tuxedo drivers. 

I've already pushed out those custom images. I've tested both the Tuxedo Control Panel and tuxedo-rs personally on Bluefin-dx, and they both worked. Feel free to test them out.

To do so, you can use rpm-ostree to rebase to my images:

`rpm-ostree rebase ostree-unverified-registry:ghcr.io/brickman240/...:latest`

Replace the "..." with the appropriate image name. It starts with "tuxedo" if you want to use the official Tuxedo Control Center, or "tuxedo-rs" if you want tuxedo-rs with its tailor-gui, and continues with the image name the official Ublue images would normally have.

Example:
`rpm-ostree rebase ostree-unverified-registry:ghcr.io/brickman240/tuxedo-bazzite-nvidia-open:latest`

Link to repos:

[ublue-tuxedo-tcc](https://github.com/BrickMan240/ublue-tuxedo-tcc)

[ublue-tuxedo-rs](https://github.com/BrickMan240/ublue-tuxedo-rs)

**Comment by castrojo** [comment]
That's awesome, good to know it works! We just need to get all this stuff in akmods/main, but we still haven't consolidated those yet. But we should get these in if they're working for people, it's just a matter of finding the time and reviewers.

**Comment by BrickMan240** [comment]
@castrojo Of course. I made these mainly as a temporary solution for people who really want to use Universal Blue on their devices before the drivers are officially added, and to offer an easy way for willing testers to try it. Hope it speeds things along, and good luck.

@tobehn Still willing to test it out?

**Comment by gagbo** [comment]
Is there a way to use a bazzite image with the work you've done to test? I just started using `aurora` on my thinkpad, and I'd like to try Bazzite on my tuxedo, but was always afraid of immutable OS because of this issue

**Comment by PerpetualWar** [comment]
@BrickMan240  I'm using immutable fedora sway (sericea). Can I use your image?
